# Default values for the artifactory-jcr chart.

systemName: jcr

repoTypes:
  - docker

image:
  repository: releases-docker.jfrog.io/jfrog/artifactory-jcr

service:
  port: 8082
  targetPort: 8082
  name: artjcrport
