# Default values for the artifactory-oss chart

systemName: oss

repoTypes:
  - maven

image:
  repository: releases-docker.jfrog.io/jfrog/artifactory-oss

service:
  port: 8082
  targetPort: 8082
  name: artossport

cleanup:
  image:
    repository: artifactory-jcr.infra/docker-local/org.nguiland.infra/alpine-ops-toolkit
    tag: "1.0.0"
  extraConfigMaps:
    - artifactory-oss-extra-cleanup-scripts
  envMap:
    ART_OSS_URL: "http://localhost:8082/artifactory"
    REPO: "libs-snapshot-local"
    KEEP: "5"
    MAX_AGE_HOURS: "6"
    DRY_RUN: "false"
    MAX_PARALLEL: "10"
    RETRIES: "3"
  env:
    - name: ART_OSS_USER
      valueFrom:
        secretKeyRef:
          name: artifactory-oss
          key: user
    - name: ART_OSS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: artifactory-oss
          key: password
