apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "git-event-listener.clusterRoleName" . }}
rules:
  - apiGroups:
      - cicd.nguiland.io
    resources:
      - dependencygraphs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "git-event-listener.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "git-event-listener.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "git-event-listener.clusterRoleName" . }}
