apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "git-event-listener.fullname" . }}
rules:
  - apiGroups:
      - cicd.nguiland.io
    resources:
      - dependencygraphs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "git-event-listener.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "git-event-listener.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "git-event-listener.fullname" . }}
